// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cosmos/erc20/v1/tx.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Imversed.Erc20.V1 {
  /// <summary>
  /// Msg defines the erc20 Msg service.
  /// </summary>
  public static partial class Msg
  {
    static readonly string __ServiceName = "imversed.erc20.v1.Msg";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Imversed.Erc20.V1.MsgConvertCoin> __Marshaller_imversed_erc20_v1_MsgConvertCoin = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Imversed.Erc20.V1.MsgConvertCoin.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Imversed.Erc20.V1.MsgConvertCoinResponse> __Marshaller_imversed_erc20_v1_MsgConvertCoinResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Imversed.Erc20.V1.MsgConvertCoinResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Imversed.Erc20.V1.MsgConvertERC20> __Marshaller_imversed_erc20_v1_MsgConvertERC20 = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Imversed.Erc20.V1.MsgConvertERC20.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Imversed.Erc20.V1.MsgConvertERC20Response> __Marshaller_imversed_erc20_v1_MsgConvertERC20Response = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Imversed.Erc20.V1.MsgConvertERC20Response.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Imversed.Erc20.V1.MsgConvertCoin, global::Imversed.Erc20.V1.MsgConvertCoinResponse> __Method_ConvertCoin = new grpc::Method<global::Imversed.Erc20.V1.MsgConvertCoin, global::Imversed.Erc20.V1.MsgConvertCoinResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ConvertCoin",
        __Marshaller_imversed_erc20_v1_MsgConvertCoin,
        __Marshaller_imversed_erc20_v1_MsgConvertCoinResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Imversed.Erc20.V1.MsgConvertERC20, global::Imversed.Erc20.V1.MsgConvertERC20Response> __Method_ConvertERC20 = new grpc::Method<global::Imversed.Erc20.V1.MsgConvertERC20, global::Imversed.Erc20.V1.MsgConvertERC20Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ConvertERC20",
        __Marshaller_imversed_erc20_v1_MsgConvertERC20,
        __Marshaller_imversed_erc20_v1_MsgConvertERC20Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Imversed.Erc20.V1.TxReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Msg</summary>
    [grpc::BindServiceMethod(typeof(Msg), "BindService")]
    public abstract partial class MsgBase
    {
      /// <summary>
      /// ConvertCoin mints a ERC20 representation of the SDK Coin denom that is
      /// registered on the token mapping.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Imversed.Erc20.V1.MsgConvertCoinResponse> ConvertCoin(global::Imversed.Erc20.V1.MsgConvertCoin request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// ConvertERC20 mints a Cosmos coin representation of the ERC20 token contract
      /// that is registered on the token mapping.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Imversed.Erc20.V1.MsgConvertERC20Response> ConvertERC20(global::Imversed.Erc20.V1.MsgConvertERC20 request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Msg</summary>
    public partial class MsgClient : grpc::ClientBase<MsgClient>
    {
      /// <summary>Creates a new client for Msg</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MsgClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Msg that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MsgClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MsgClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MsgClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// ConvertCoin mints a ERC20 representation of the SDK Coin denom that is
      /// registered on the token mapping.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Imversed.Erc20.V1.MsgConvertCoinResponse ConvertCoin(global::Imversed.Erc20.V1.MsgConvertCoin request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConvertCoin(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// ConvertCoin mints a ERC20 representation of the SDK Coin denom that is
      /// registered on the token mapping.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Imversed.Erc20.V1.MsgConvertCoinResponse ConvertCoin(global::Imversed.Erc20.V1.MsgConvertCoin request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ConvertCoin, null, options, request);
      }
      /// <summary>
      /// ConvertCoin mints a ERC20 representation of the SDK Coin denom that is
      /// registered on the token mapping.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Imversed.Erc20.V1.MsgConvertCoinResponse> ConvertCoinAsync(global::Imversed.Erc20.V1.MsgConvertCoin request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConvertCoinAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// ConvertCoin mints a ERC20 representation of the SDK Coin denom that is
      /// registered on the token mapping.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Imversed.Erc20.V1.MsgConvertCoinResponse> ConvertCoinAsync(global::Imversed.Erc20.V1.MsgConvertCoin request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ConvertCoin, null, options, request);
      }
      /// <summary>
      /// ConvertERC20 mints a Cosmos coin representation of the ERC20 token contract
      /// that is registered on the token mapping.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Imversed.Erc20.V1.MsgConvertERC20Response ConvertERC20(global::Imversed.Erc20.V1.MsgConvertERC20 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConvertERC20(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// ConvertERC20 mints a Cosmos coin representation of the ERC20 token contract
      /// that is registered on the token mapping.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Imversed.Erc20.V1.MsgConvertERC20Response ConvertERC20(global::Imversed.Erc20.V1.MsgConvertERC20 request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ConvertERC20, null, options, request);
      }
      /// <summary>
      /// ConvertERC20 mints a Cosmos coin representation of the ERC20 token contract
      /// that is registered on the token mapping.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Imversed.Erc20.V1.MsgConvertERC20Response> ConvertERC20Async(global::Imversed.Erc20.V1.MsgConvertERC20 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConvertERC20Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// ConvertERC20 mints a Cosmos coin representation of the ERC20 token contract
      /// that is registered on the token mapping.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Imversed.Erc20.V1.MsgConvertERC20Response> ConvertERC20Async(global::Imversed.Erc20.V1.MsgConvertERC20 request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ConvertERC20, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override MsgClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MsgClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(MsgBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ConvertCoin, serviceImpl.ConvertCoin)
          .AddMethod(__Method_ConvertERC20, serviceImpl.ConvertERC20).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MsgBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ConvertCoin, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Imversed.Erc20.V1.MsgConvertCoin, global::Imversed.Erc20.V1.MsgConvertCoinResponse>(serviceImpl.ConvertCoin));
      serviceBinder.AddMethod(__Method_ConvertERC20, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Imversed.Erc20.V1.MsgConvertERC20, global::Imversed.Erc20.V1.MsgConvertERC20Response>(serviceImpl.ConvertERC20));
    }

  }
}
#endregion
