// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cosmos/msg/v1/msg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cosmos.Msg.V1 {

  /// <summary>Holder for reflection information generated from cosmos/msg/v1/msg.proto</summary>
  public static partial class MsgReflection {

    #region Descriptor
    /// <summary>File descriptor for cosmos/msg/v1/msg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chdjb3Ntb3MvbXNnL3YxL21zZy5wcm90bxINY29zbW9zLm1zZy52MRogZ29v",
            "Z2xlL3Byb3RvYnVmL2Rlc2NyaXB0b3IucHJvdG86MgoGc2lnbmVyEh8uZ29v",
            "Z2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGPCMpgUgAygJQi9aLWdpdGh1",
            "Yi5jb20vY29zbW9zL2Nvc21vcy1zZGsvdHlwZXMvbXNnc2VydmljZWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { MsgExtensions.Signer }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of cosmos/msg/v1/msg.proto</summary>
  public static partial class MsgExtensions {
    /// <summary>
    /// signer must be used in cosmos messages in order
    /// to signal to external clients which fields in a
    /// given cosmos message must be filled with signer
    /// information (address).
    /// The field must be the protobuf name of the message
    /// field extended with this MessageOption.
    /// The field must either be of string kind, or of message
    /// kind in case the signer information is contained within
    /// a message inside the cosmos message.
    /// </summary>
    public static readonly pb::RepeatedExtension<global::Google.Protobuf.Reflection.MessageOptions, string> Signer =
      new pb::RepeatedExtension<global::Google.Protobuf.Reflection.MessageOptions, string>(11110000, pb::FieldCodec.ForString(88880002));
  }

}

#endregion Designer generated code
