// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cosmos/gov/v1/gov.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cosmos.Gov.V1 {

  /// <summary>Holder for reflection information generated from cosmos/gov/v1/gov.proto</summary>
  public static partial class GovReflection {

    #region Descriptor
    /// <summary>File descriptor for cosmos/gov/v1/gov.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GovReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chdjb3Ntb3MvZ292L3YxL2dvdi5wcm90bxINY29zbW9zLmdvdi52MRoeY29z",
            "bW9zL2Jhc2UvdjFiZXRhMS9jb2luLnByb3RvGhRnb2dvcHJvdG8vZ29nby5w",
            "cm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90bxoZZ29vZ2xl",
            "L3Byb3RvYnVmL2FueS5wcm90bxoeZ29vZ2xlL3Byb3RvYnVmL2R1cmF0aW9u",
            "LnByb3RvGhljb3Ntb3NfcHJvdG8vY29zbW9zLnByb3RvIl8KEldlaWdodGVk",
            "Vm90ZU9wdGlvbhIpCgZvcHRpb24YASABKA4yGS5jb3Ntb3MuZ292LnYxLlZv",
            "dGVPcHRpb24SHgoGd2VpZ2h0GAIgASgJQg7StC0KY29zbW9zLkRlYyJ8CgdE",
            "ZXBvc2l0EhMKC3Byb3Bvc2FsX2lkGAEgASgEEisKCWRlcG9zaXRvchgCIAEo",
            "CUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nEi8KBmFtb3VudBgDIAMoCzIZ",
            "LmNvc21vcy5iYXNlLnYxYmV0YTEuQ29pbkIEyN4fACLaAwoIUHJvcG9zYWwS",
            "CgoCaWQYASABKAQSJgoIbWVzc2FnZXMYAiADKAsyFC5nb29nbGUucHJvdG9i",
            "dWYuQW55Ei0KBnN0YXR1cxgDIAEoDjIdLmNvc21vcy5nb3YudjEuUHJvcG9z",
            "YWxTdGF0dXMSNgoSZmluYWxfdGFsbHlfcmVzdWx0GAQgASgLMhouY29zbW9z",
            "Lmdvdi52MS5UYWxseVJlc3VsdBI1CgtzdWJtaXRfdGltZRgFIAEoCzIaLmdv",
            "b2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCBJDfHwESOgoQZGVwb3NpdF9lbmRf",
            "dGltZRgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCBJDfHwES",
            "NgoNdG90YWxfZGVwb3NpdBgHIAMoCzIZLmNvc21vcy5iYXNlLnYxYmV0YTEu",
            "Q29pbkIEyN4fABI7ChF2b3Rpbmdfc3RhcnRfdGltZRgIIAEoCzIaLmdvb2ds",
            "ZS5wcm90b2J1Zi5UaW1lc3RhbXBCBJDfHwESOQoPdm90aW5nX2VuZF90aW1l",
            "GAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIEkN8fARIQCght",
            "ZXRhZGF0YRgKIAEoCSKlAQoLVGFsbHlSZXN1bHQSIQoJeWVzX2NvdW50GAEg",
            "ASgJQg7StC0KY29zbW9zLkludBIlCg1hYnN0YWluX2NvdW50GAIgASgJQg7S",
            "tC0KY29zbW9zLkludBIgCghub19jb3VudBgDIAEoCUIO0rQtCmNvc21vcy5J",
            "bnQSKgoSbm9fd2l0aF92ZXRvX2NvdW50GAQgASgJQg7StC0KY29zbW9zLklu",
            "dCKQAQoEVm90ZRITCgtwcm9wb3NhbF9pZBgBIAEoBBInCgV2b3RlchgCIAEo",
            "CUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nEjIKB29wdGlvbnMYBCADKAsy",
            "IS5jb3Ntb3MuZ292LnYxLldlaWdodGVkVm90ZU9wdGlvbhIQCghtZXRhZGF0",
            "YRgFIAEoCUoECAMQBCK7AQoNRGVwb3NpdFBhcmFtcxJNCgttaW5fZGVwb3Np",
            "dBgBIAMoCzIZLmNvc21vcy5iYXNlLnYxYmV0YTEuQ29pbkIdyN4fAOreHxVt",
            "aW5fZGVwb3NpdCxvbWl0ZW1wdHkSWwoSbWF4X2RlcG9zaXRfcGVyaW9kGAIg",
            "ASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uQiSY3x8B6t4fHG1heF9k",
            "ZXBvc2l0X3BlcmlvZCxvbWl0ZW1wdHkiRgoMVm90aW5nUGFyYW1zEjYKDXZv",
            "dGluZ19wZXJpb2QYASABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb25C",
            "BJjfHwEivwEKC1RhbGx5UGFyYW1zEjIKBnF1b3J1bRgBIAEoCUIi0rQtCmNv",
            "c21vcy5EZWPq3h8QcXVvcnVtLG9taXRlbXB0eRI4Cgl0aHJlc2hvbGQYAiAB",
            "KAlCJdK0LQpjb3Ntb3MuRGVj6t4fE3RocmVzaG9sZCxvbWl0ZW1wdHkSQgoO",
            "dmV0b190aHJlc2hvbGQYAyABKAlCKtK0LQpjb3Ntb3MuRGVj6t4fGHZldG9f",
            "dGhyZXNob2xkLG9taXRlbXB0eSqJAQoKVm90ZU9wdGlvbhIbChdWT1RFX09Q",
            "VElPTl9VTlNQRUNJRklFRBAAEhMKD1ZPVEVfT1BUSU9OX1lFUxABEhcKE1ZP",
            "VEVfT1BUSU9OX0FCU1RBSU4QAhISCg5WT1RFX09QVElPTl9OTxADEhwKGFZP",
            "VEVfT1BUSU9OX05PX1dJVEhfVkVUTxAEKs4BCg5Qcm9wb3NhbFN0YXR1cxIf",
            "ChtQUk9QT1NBTF9TVEFUVVNfVU5TUEVDSUZJRUQQABIiCh5QUk9QT1NBTF9T",
            "VEFUVVNfREVQT1NJVF9QRVJJT0QQARIhCh1QUk9QT1NBTF9TVEFUVVNfVk9U",
            "SU5HX1BFUklPRBACEhoKFlBST1BPU0FMX1NUQVRVU19QQVNTRUQQAxIcChhQ",
            "Uk9QT1NBTF9TVEFUVVNfUkVKRUNURUQQBBIaChZQUk9QT1NBTF9TVEFUVVNf",
            "RkFJTEVEEAVCLVorZ2l0aHViLmNvbS9jb3Ntb3MvY29zbW9zLXNkay94L2dv",
            "di90eXBlcy92MWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Cosmos.Base.V1Beta1.CoinReflection.Descriptor, global::Gogoproto.GogoReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, global::CosmosProto.CosmosReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Cosmos.Gov.V1.VoteOption), typeof(global::Cosmos.Gov.V1.ProposalStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Cosmos.Gov.V1.WeightedVoteOption), global::Cosmos.Gov.V1.WeightedVoteOption.Parser, new[]{ "Option", "Weight" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cosmos.Gov.V1.Deposit), global::Cosmos.Gov.V1.Deposit.Parser, new[]{ "ProposalId", "Depositor", "Amount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cosmos.Gov.V1.Proposal), global::Cosmos.Gov.V1.Proposal.Parser, new[]{ "Id", "Messages", "Status", "FinalTallyResult", "SubmitTime", "DepositEndTime", "TotalDeposit", "VotingStartTime", "VotingEndTime", "Metadata" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cosmos.Gov.V1.TallyResult), global::Cosmos.Gov.V1.TallyResult.Parser, new[]{ "YesCount", "AbstainCount", "NoCount", "NoWithVetoCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cosmos.Gov.V1.Vote), global::Cosmos.Gov.V1.Vote.Parser, new[]{ "ProposalId", "Voter", "Options", "Metadata" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cosmos.Gov.V1.DepositParams), global::Cosmos.Gov.V1.DepositParams.Parser, new[]{ "MinDeposit", "MaxDepositPeriod" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cosmos.Gov.V1.VotingParams), global::Cosmos.Gov.V1.VotingParams.Parser, new[]{ "VotingPeriod" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cosmos.Gov.V1.TallyParams), global::Cosmos.Gov.V1.TallyParams.Parser, new[]{ "Quorum", "Threshold", "VetoThreshold" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// VoteOption enumerates the valid vote options for a given governance proposal.
  /// </summary>
  public enum VoteOption {
    /// <summary>
    /// VOTE_OPTION_UNSPECIFIED defines a no-op vote option.
    /// </summary>
    [pbr::OriginalName("VOTE_OPTION_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// VOTE_OPTION_YES defines a yes vote option.
    /// </summary>
    [pbr::OriginalName("VOTE_OPTION_YES")] Yes = 1,
    /// <summary>
    /// VOTE_OPTION_ABSTAIN defines an abstain vote option.
    /// </summary>
    [pbr::OriginalName("VOTE_OPTION_ABSTAIN")] Abstain = 2,
    /// <summary>
    /// VOTE_OPTION_NO defines a no vote option.
    /// </summary>
    [pbr::OriginalName("VOTE_OPTION_NO")] No = 3,
    /// <summary>
    /// VOTE_OPTION_NO_WITH_VETO defines a no with veto vote option.
    /// </summary>
    [pbr::OriginalName("VOTE_OPTION_NO_WITH_VETO")] NoWithVeto = 4,
  }

  /// <summary>
  /// ProposalStatus enumerates the valid statuses of a proposal.
  /// </summary>
  public enum ProposalStatus {
    /// <summary>
    /// PROPOSAL_STATUS_UNSPECIFIED defines the default proposal status.
    /// </summary>
    [pbr::OriginalName("PROPOSAL_STATUS_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// PROPOSAL_STATUS_DEPOSIT_PERIOD defines a proposal status during the deposit
    /// period.
    /// </summary>
    [pbr::OriginalName("PROPOSAL_STATUS_DEPOSIT_PERIOD")] DepositPeriod = 1,
    /// <summary>
    /// PROPOSAL_STATUS_VOTING_PERIOD defines a proposal status during the voting
    /// period.
    /// </summary>
    [pbr::OriginalName("PROPOSAL_STATUS_VOTING_PERIOD")] VotingPeriod = 2,
    /// <summary>
    /// PROPOSAL_STATUS_PASSED defines a proposal status of a proposal that has
    /// passed.
    /// </summary>
    [pbr::OriginalName("PROPOSAL_STATUS_PASSED")] Passed = 3,
    /// <summary>
    /// PROPOSAL_STATUS_REJECTED defines a proposal status of a proposal that has
    /// been rejected.
    /// </summary>
    [pbr::OriginalName("PROPOSAL_STATUS_REJECTED")] Rejected = 4,
    /// <summary>
    /// PROPOSAL_STATUS_FAILED defines a proposal status of a proposal that has
    /// failed.
    /// </summary>
    [pbr::OriginalName("PROPOSAL_STATUS_FAILED")] Failed = 5,
  }

  #endregion

  #region Messages
  /// <summary>
  /// WeightedVoteOption defines a unit of vote for vote split.
  /// </summary>
  public sealed partial class WeightedVoteOption : pb::IMessage<WeightedVoteOption>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WeightedVoteOption> _parser = new pb::MessageParser<WeightedVoteOption>(() => new WeightedVoteOption());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WeightedVoteOption> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cosmos.Gov.V1.GovReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WeightedVoteOption() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WeightedVoteOption(WeightedVoteOption other) : this() {
      option_ = other.option_;
      weight_ = other.weight_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WeightedVoteOption Clone() {
      return new WeightedVoteOption(this);
    }

    /// <summary>Field number for the "option" field.</summary>
    public const int OptionFieldNumber = 1;
    private global::Cosmos.Gov.V1.VoteOption option_ = global::Cosmos.Gov.V1.VoteOption.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cosmos.Gov.V1.VoteOption Option {
      get { return option_; }
      set {
        option_ = value;
      }
    }

    /// <summary>Field number for the "weight" field.</summary>
    public const int WeightFieldNumber = 2;
    private string weight_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Weight {
      get { return weight_; }
      set {
        weight_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WeightedVoteOption);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WeightedVoteOption other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Option != other.Option) return false;
      if (Weight != other.Weight) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Option != global::Cosmos.Gov.V1.VoteOption.Unspecified) hash ^= Option.GetHashCode();
      if (Weight.Length != 0) hash ^= Weight.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Option != global::Cosmos.Gov.V1.VoteOption.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Option);
      }
      if (Weight.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Weight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Option != global::Cosmos.Gov.V1.VoteOption.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Option);
      }
      if (Weight.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Weight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Option != global::Cosmos.Gov.V1.VoteOption.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Option);
      }
      if (Weight.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Weight);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WeightedVoteOption other) {
      if (other == null) {
        return;
      }
      if (other.Option != global::Cosmos.Gov.V1.VoteOption.Unspecified) {
        Option = other.Option;
      }
      if (other.Weight.Length != 0) {
        Weight = other.Weight;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Option = (global::Cosmos.Gov.V1.VoteOption) input.ReadEnum();
            break;
          }
          case 18: {
            Weight = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Option = (global::Cosmos.Gov.V1.VoteOption) input.ReadEnum();
            break;
          }
          case 18: {
            Weight = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Deposit defines an amount deposited by an account address to an active
  /// proposal.
  /// </summary>
  public sealed partial class Deposit : pb::IMessage<Deposit>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Deposit> _parser = new pb::MessageParser<Deposit>(() => new Deposit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Deposit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cosmos.Gov.V1.GovReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Deposit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Deposit(Deposit other) : this() {
      proposalId_ = other.proposalId_;
      depositor_ = other.depositor_;
      amount_ = other.amount_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Deposit Clone() {
      return new Deposit(this);
    }

    /// <summary>Field number for the "proposal_id" field.</summary>
    public const int ProposalIdFieldNumber = 1;
    private ulong proposalId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ProposalId {
      get { return proposalId_; }
      set {
        proposalId_ = value;
      }
    }

    /// <summary>Field number for the "depositor" field.</summary>
    public const int DepositorFieldNumber = 2;
    private string depositor_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Depositor {
      get { return depositor_; }
      set {
        depositor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "amount" field.</summary>
    public const int AmountFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Cosmos.Base.V1Beta1.Coin> _repeated_amount_codec
        = pb::FieldCodec.ForMessage(26, global::Cosmos.Base.V1Beta1.Coin.Parser);
    private readonly pbc::RepeatedField<global::Cosmos.Base.V1Beta1.Coin> amount_ = new pbc::RepeatedField<global::Cosmos.Base.V1Beta1.Coin>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Cosmos.Base.V1Beta1.Coin> Amount {
      get { return amount_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Deposit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Deposit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProposalId != other.ProposalId) return false;
      if (Depositor != other.Depositor) return false;
      if(!amount_.Equals(other.amount_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProposalId != 0UL) hash ^= ProposalId.GetHashCode();
      if (Depositor.Length != 0) hash ^= Depositor.GetHashCode();
      hash ^= amount_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProposalId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ProposalId);
      }
      if (Depositor.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Depositor);
      }
      amount_.WriteTo(output, _repeated_amount_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProposalId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ProposalId);
      }
      if (Depositor.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Depositor);
      }
      amount_.WriteTo(ref output, _repeated_amount_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProposalId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ProposalId);
      }
      if (Depositor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Depositor);
      }
      size += amount_.CalculateSize(_repeated_amount_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Deposit other) {
      if (other == null) {
        return;
      }
      if (other.ProposalId != 0UL) {
        ProposalId = other.ProposalId;
      }
      if (other.Depositor.Length != 0) {
        Depositor = other.Depositor;
      }
      amount_.Add(other.amount_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProposalId = input.ReadUInt64();
            break;
          }
          case 18: {
            Depositor = input.ReadString();
            break;
          }
          case 26: {
            amount_.AddEntriesFrom(input, _repeated_amount_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProposalId = input.ReadUInt64();
            break;
          }
          case 18: {
            Depositor = input.ReadString();
            break;
          }
          case 26: {
            amount_.AddEntriesFrom(ref input, _repeated_amount_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Proposal defines the core field members of a governance proposal.
  /// </summary>
  public sealed partial class Proposal : pb::IMessage<Proposal>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Proposal> _parser = new pb::MessageParser<Proposal>(() => new Proposal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Proposal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cosmos.Gov.V1.GovReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Proposal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Proposal(Proposal other) : this() {
      id_ = other.id_;
      messages_ = other.messages_.Clone();
      status_ = other.status_;
      finalTallyResult_ = other.finalTallyResult_ != null ? other.finalTallyResult_.Clone() : null;
      submitTime_ = other.submitTime_ != null ? other.submitTime_.Clone() : null;
      depositEndTime_ = other.depositEndTime_ != null ? other.depositEndTime_.Clone() : null;
      totalDeposit_ = other.totalDeposit_.Clone();
      votingStartTime_ = other.votingStartTime_ != null ? other.votingStartTime_.Clone() : null;
      votingEndTime_ = other.votingEndTime_ != null ? other.votingEndTime_.Clone() : null;
      metadata_ = other.metadata_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Proposal Clone() {
      return new Proposal(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private ulong id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "messages" field.</summary>
    public const int MessagesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Google.Protobuf.WellKnownTypes.Any> _repeated_messages_codec
        = pb::FieldCodec.ForMessage(18, global::Google.Protobuf.WellKnownTypes.Any.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> messages_ = new pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> Messages {
      get { return messages_; }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 3;
    private global::Cosmos.Gov.V1.ProposalStatus status_ = global::Cosmos.Gov.V1.ProposalStatus.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cosmos.Gov.V1.ProposalStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "final_tally_result" field.</summary>
    public const int FinalTallyResultFieldNumber = 4;
    private global::Cosmos.Gov.V1.TallyResult finalTallyResult_;
    /// <summary>
    /// final_tally_result is the final tally result of the proposal. When
    /// querying a proposal via gRPC, this field is not populated until the
    /// proposal's voting period has ended.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cosmos.Gov.V1.TallyResult FinalTallyResult {
      get { return finalTallyResult_; }
      set {
        finalTallyResult_ = value;
      }
    }

    /// <summary>Field number for the "submit_time" field.</summary>
    public const int SubmitTimeFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Timestamp submitTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp SubmitTime {
      get { return submitTime_; }
      set {
        submitTime_ = value;
      }
    }

    /// <summary>Field number for the "deposit_end_time" field.</summary>
    public const int DepositEndTimeFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Timestamp depositEndTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DepositEndTime {
      get { return depositEndTime_; }
      set {
        depositEndTime_ = value;
      }
    }

    /// <summary>Field number for the "total_deposit" field.</summary>
    public const int TotalDepositFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Cosmos.Base.V1Beta1.Coin> _repeated_totalDeposit_codec
        = pb::FieldCodec.ForMessage(58, global::Cosmos.Base.V1Beta1.Coin.Parser);
    private readonly pbc::RepeatedField<global::Cosmos.Base.V1Beta1.Coin> totalDeposit_ = new pbc::RepeatedField<global::Cosmos.Base.V1Beta1.Coin>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Cosmos.Base.V1Beta1.Coin> TotalDeposit {
      get { return totalDeposit_; }
    }

    /// <summary>Field number for the "voting_start_time" field.</summary>
    public const int VotingStartTimeFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Timestamp votingStartTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp VotingStartTime {
      get { return votingStartTime_; }
      set {
        votingStartTime_ = value;
      }
    }

    /// <summary>Field number for the "voting_end_time" field.</summary>
    public const int VotingEndTimeFieldNumber = 9;
    private global::Google.Protobuf.WellKnownTypes.Timestamp votingEndTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp VotingEndTime {
      get { return votingEndTime_; }
      set {
        votingEndTime_ = value;
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 10;
    private string metadata_ = "";
    /// <summary>
    /// metadata is any arbitrary metadata attached to the proposal.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Metadata {
      get { return metadata_; }
      set {
        metadata_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Proposal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Proposal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if(!messages_.Equals(other.messages_)) return false;
      if (Status != other.Status) return false;
      if (!object.Equals(FinalTallyResult, other.FinalTallyResult)) return false;
      if (!object.Equals(SubmitTime, other.SubmitTime)) return false;
      if (!object.Equals(DepositEndTime, other.DepositEndTime)) return false;
      if(!totalDeposit_.Equals(other.totalDeposit_)) return false;
      if (!object.Equals(VotingStartTime, other.VotingStartTime)) return false;
      if (!object.Equals(VotingEndTime, other.VotingEndTime)) return false;
      if (Metadata != other.Metadata) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0UL) hash ^= Id.GetHashCode();
      hash ^= messages_.GetHashCode();
      if (Status != global::Cosmos.Gov.V1.ProposalStatus.Unspecified) hash ^= Status.GetHashCode();
      if (finalTallyResult_ != null) hash ^= FinalTallyResult.GetHashCode();
      if (submitTime_ != null) hash ^= SubmitTime.GetHashCode();
      if (depositEndTime_ != null) hash ^= DepositEndTime.GetHashCode();
      hash ^= totalDeposit_.GetHashCode();
      if (votingStartTime_ != null) hash ^= VotingStartTime.GetHashCode();
      if (votingEndTime_ != null) hash ^= VotingEndTime.GetHashCode();
      if (Metadata.Length != 0) hash ^= Metadata.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Id);
      }
      messages_.WriteTo(output, _repeated_messages_codec);
      if (Status != global::Cosmos.Gov.V1.ProposalStatus.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (finalTallyResult_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FinalTallyResult);
      }
      if (submitTime_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(SubmitTime);
      }
      if (depositEndTime_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(DepositEndTime);
      }
      totalDeposit_.WriteTo(output, _repeated_totalDeposit_codec);
      if (votingStartTime_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(VotingStartTime);
      }
      if (votingEndTime_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(VotingEndTime);
      }
      if (Metadata.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Metadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Id);
      }
      messages_.WriteTo(ref output, _repeated_messages_codec);
      if (Status != global::Cosmos.Gov.V1.ProposalStatus.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (finalTallyResult_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FinalTallyResult);
      }
      if (submitTime_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(SubmitTime);
      }
      if (depositEndTime_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(DepositEndTime);
      }
      totalDeposit_.WriteTo(ref output, _repeated_totalDeposit_codec);
      if (votingStartTime_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(VotingStartTime);
      }
      if (votingEndTime_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(VotingEndTime);
      }
      if (Metadata.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Metadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
      }
      size += messages_.CalculateSize(_repeated_messages_codec);
      if (Status != global::Cosmos.Gov.V1.ProposalStatus.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (finalTallyResult_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FinalTallyResult);
      }
      if (submitTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SubmitTime);
      }
      if (depositEndTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DepositEndTime);
      }
      size += totalDeposit_.CalculateSize(_repeated_totalDeposit_codec);
      if (votingStartTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VotingStartTime);
      }
      if (votingEndTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VotingEndTime);
      }
      if (Metadata.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Metadata);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Proposal other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0UL) {
        Id = other.Id;
      }
      messages_.Add(other.messages_);
      if (other.Status != global::Cosmos.Gov.V1.ProposalStatus.Unspecified) {
        Status = other.Status;
      }
      if (other.finalTallyResult_ != null) {
        if (finalTallyResult_ == null) {
          FinalTallyResult = new global::Cosmos.Gov.V1.TallyResult();
        }
        FinalTallyResult.MergeFrom(other.FinalTallyResult);
      }
      if (other.submitTime_ != null) {
        if (submitTime_ == null) {
          SubmitTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        SubmitTime.MergeFrom(other.SubmitTime);
      }
      if (other.depositEndTime_ != null) {
        if (depositEndTime_ == null) {
          DepositEndTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DepositEndTime.MergeFrom(other.DepositEndTime);
      }
      totalDeposit_.Add(other.totalDeposit_);
      if (other.votingStartTime_ != null) {
        if (votingStartTime_ == null) {
          VotingStartTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        VotingStartTime.MergeFrom(other.VotingStartTime);
      }
      if (other.votingEndTime_ != null) {
        if (votingEndTime_ == null) {
          VotingEndTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        VotingEndTime.MergeFrom(other.VotingEndTime);
      }
      if (other.Metadata.Length != 0) {
        Metadata = other.Metadata;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt64();
            break;
          }
          case 18: {
            messages_.AddEntriesFrom(input, _repeated_messages_codec);
            break;
          }
          case 24: {
            Status = (global::Cosmos.Gov.V1.ProposalStatus) input.ReadEnum();
            break;
          }
          case 34: {
            if (finalTallyResult_ == null) {
              FinalTallyResult = new global::Cosmos.Gov.V1.TallyResult();
            }
            input.ReadMessage(FinalTallyResult);
            break;
          }
          case 42: {
            if (submitTime_ == null) {
              SubmitTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(SubmitTime);
            break;
          }
          case 50: {
            if (depositEndTime_ == null) {
              DepositEndTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DepositEndTime);
            break;
          }
          case 58: {
            totalDeposit_.AddEntriesFrom(input, _repeated_totalDeposit_codec);
            break;
          }
          case 66: {
            if (votingStartTime_ == null) {
              VotingStartTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(VotingStartTime);
            break;
          }
          case 74: {
            if (votingEndTime_ == null) {
              VotingEndTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(VotingEndTime);
            break;
          }
          case 82: {
            Metadata = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadUInt64();
            break;
          }
          case 18: {
            messages_.AddEntriesFrom(ref input, _repeated_messages_codec);
            break;
          }
          case 24: {
            Status = (global::Cosmos.Gov.V1.ProposalStatus) input.ReadEnum();
            break;
          }
          case 34: {
            if (finalTallyResult_ == null) {
              FinalTallyResult = new global::Cosmos.Gov.V1.TallyResult();
            }
            input.ReadMessage(FinalTallyResult);
            break;
          }
          case 42: {
            if (submitTime_ == null) {
              SubmitTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(SubmitTime);
            break;
          }
          case 50: {
            if (depositEndTime_ == null) {
              DepositEndTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DepositEndTime);
            break;
          }
          case 58: {
            totalDeposit_.AddEntriesFrom(ref input, _repeated_totalDeposit_codec);
            break;
          }
          case 66: {
            if (votingStartTime_ == null) {
              VotingStartTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(VotingStartTime);
            break;
          }
          case 74: {
            if (votingEndTime_ == null) {
              VotingEndTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(VotingEndTime);
            break;
          }
          case 82: {
            Metadata = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// TallyResult defines a standard tally for a governance proposal.
  /// </summary>
  public sealed partial class TallyResult : pb::IMessage<TallyResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TallyResult> _parser = new pb::MessageParser<TallyResult>(() => new TallyResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TallyResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cosmos.Gov.V1.GovReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TallyResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TallyResult(TallyResult other) : this() {
      yesCount_ = other.yesCount_;
      abstainCount_ = other.abstainCount_;
      noCount_ = other.noCount_;
      noWithVetoCount_ = other.noWithVetoCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TallyResult Clone() {
      return new TallyResult(this);
    }

    /// <summary>Field number for the "yes_count" field.</summary>
    public const int YesCountFieldNumber = 1;
    private string yesCount_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string YesCount {
      get { return yesCount_; }
      set {
        yesCount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "abstain_count" field.</summary>
    public const int AbstainCountFieldNumber = 2;
    private string abstainCount_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AbstainCount {
      get { return abstainCount_; }
      set {
        abstainCount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "no_count" field.</summary>
    public const int NoCountFieldNumber = 3;
    private string noCount_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NoCount {
      get { return noCount_; }
      set {
        noCount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "no_with_veto_count" field.</summary>
    public const int NoWithVetoCountFieldNumber = 4;
    private string noWithVetoCount_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NoWithVetoCount {
      get { return noWithVetoCount_; }
      set {
        noWithVetoCount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TallyResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TallyResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (YesCount != other.YesCount) return false;
      if (AbstainCount != other.AbstainCount) return false;
      if (NoCount != other.NoCount) return false;
      if (NoWithVetoCount != other.NoWithVetoCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (YesCount.Length != 0) hash ^= YesCount.GetHashCode();
      if (AbstainCount.Length != 0) hash ^= AbstainCount.GetHashCode();
      if (NoCount.Length != 0) hash ^= NoCount.GetHashCode();
      if (NoWithVetoCount.Length != 0) hash ^= NoWithVetoCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (YesCount.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(YesCount);
      }
      if (AbstainCount.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AbstainCount);
      }
      if (NoCount.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NoCount);
      }
      if (NoWithVetoCount.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NoWithVetoCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (YesCount.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(YesCount);
      }
      if (AbstainCount.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AbstainCount);
      }
      if (NoCount.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NoCount);
      }
      if (NoWithVetoCount.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NoWithVetoCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (YesCount.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(YesCount);
      }
      if (AbstainCount.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AbstainCount);
      }
      if (NoCount.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NoCount);
      }
      if (NoWithVetoCount.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NoWithVetoCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TallyResult other) {
      if (other == null) {
        return;
      }
      if (other.YesCount.Length != 0) {
        YesCount = other.YesCount;
      }
      if (other.AbstainCount.Length != 0) {
        AbstainCount = other.AbstainCount;
      }
      if (other.NoCount.Length != 0) {
        NoCount = other.NoCount;
      }
      if (other.NoWithVetoCount.Length != 0) {
        NoWithVetoCount = other.NoWithVetoCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            YesCount = input.ReadString();
            break;
          }
          case 18: {
            AbstainCount = input.ReadString();
            break;
          }
          case 26: {
            NoCount = input.ReadString();
            break;
          }
          case 34: {
            NoWithVetoCount = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            YesCount = input.ReadString();
            break;
          }
          case 18: {
            AbstainCount = input.ReadString();
            break;
          }
          case 26: {
            NoCount = input.ReadString();
            break;
          }
          case 34: {
            NoWithVetoCount = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Vote defines a vote on a governance proposal.
  /// A Vote consists of a proposal ID, the voter, and the vote option.
  /// </summary>
  public sealed partial class Vote : pb::IMessage<Vote>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Vote> _parser = new pb::MessageParser<Vote>(() => new Vote());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Vote> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cosmos.Gov.V1.GovReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vote() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vote(Vote other) : this() {
      proposalId_ = other.proposalId_;
      voter_ = other.voter_;
      options_ = other.options_.Clone();
      metadata_ = other.metadata_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vote Clone() {
      return new Vote(this);
    }

    /// <summary>Field number for the "proposal_id" field.</summary>
    public const int ProposalIdFieldNumber = 1;
    private ulong proposalId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ProposalId {
      get { return proposalId_; }
      set {
        proposalId_ = value;
      }
    }

    /// <summary>Field number for the "voter" field.</summary>
    public const int VoterFieldNumber = 2;
    private string voter_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Voter {
      get { return voter_; }
      set {
        voter_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "options" field.</summary>
    public const int OptionsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Cosmos.Gov.V1.WeightedVoteOption> _repeated_options_codec
        = pb::FieldCodec.ForMessage(34, global::Cosmos.Gov.V1.WeightedVoteOption.Parser);
    private readonly pbc::RepeatedField<global::Cosmos.Gov.V1.WeightedVoteOption> options_ = new pbc::RepeatedField<global::Cosmos.Gov.V1.WeightedVoteOption>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Cosmos.Gov.V1.WeightedVoteOption> Options {
      get { return options_; }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 5;
    private string metadata_ = "";
    /// <summary>
    /// metadata is any  arbitrary metadata to attached to the vote.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Metadata {
      get { return metadata_; }
      set {
        metadata_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Vote);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Vote other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProposalId != other.ProposalId) return false;
      if (Voter != other.Voter) return false;
      if(!options_.Equals(other.options_)) return false;
      if (Metadata != other.Metadata) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProposalId != 0UL) hash ^= ProposalId.GetHashCode();
      if (Voter.Length != 0) hash ^= Voter.GetHashCode();
      hash ^= options_.GetHashCode();
      if (Metadata.Length != 0) hash ^= Metadata.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProposalId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ProposalId);
      }
      if (Voter.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Voter);
      }
      options_.WriteTo(output, _repeated_options_codec);
      if (Metadata.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Metadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProposalId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ProposalId);
      }
      if (Voter.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Voter);
      }
      options_.WriteTo(ref output, _repeated_options_codec);
      if (Metadata.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Metadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProposalId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ProposalId);
      }
      if (Voter.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Voter);
      }
      size += options_.CalculateSize(_repeated_options_codec);
      if (Metadata.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Metadata);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Vote other) {
      if (other == null) {
        return;
      }
      if (other.ProposalId != 0UL) {
        ProposalId = other.ProposalId;
      }
      if (other.Voter.Length != 0) {
        Voter = other.Voter;
      }
      options_.Add(other.options_);
      if (other.Metadata.Length != 0) {
        Metadata = other.Metadata;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProposalId = input.ReadUInt64();
            break;
          }
          case 18: {
            Voter = input.ReadString();
            break;
          }
          case 34: {
            options_.AddEntriesFrom(input, _repeated_options_codec);
            break;
          }
          case 42: {
            Metadata = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProposalId = input.ReadUInt64();
            break;
          }
          case 18: {
            Voter = input.ReadString();
            break;
          }
          case 34: {
            options_.AddEntriesFrom(ref input, _repeated_options_codec);
            break;
          }
          case 42: {
            Metadata = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// DepositParams defines the params for deposits on governance proposals.
  /// </summary>
  public sealed partial class DepositParams : pb::IMessage<DepositParams>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DepositParams> _parser = new pb::MessageParser<DepositParams>(() => new DepositParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DepositParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cosmos.Gov.V1.GovReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DepositParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DepositParams(DepositParams other) : this() {
      minDeposit_ = other.minDeposit_.Clone();
      maxDepositPeriod_ = other.maxDepositPeriod_ != null ? other.maxDepositPeriod_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DepositParams Clone() {
      return new DepositParams(this);
    }

    /// <summary>Field number for the "min_deposit" field.</summary>
    public const int MinDepositFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Cosmos.Base.V1Beta1.Coin> _repeated_minDeposit_codec
        = pb::FieldCodec.ForMessage(10, global::Cosmos.Base.V1Beta1.Coin.Parser);
    private readonly pbc::RepeatedField<global::Cosmos.Base.V1Beta1.Coin> minDeposit_ = new pbc::RepeatedField<global::Cosmos.Base.V1Beta1.Coin>();
    /// <summary>
    ///  Minimum deposit for a proposal to enter voting period.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Cosmos.Base.V1Beta1.Coin> MinDeposit {
      get { return minDeposit_; }
    }

    /// <summary>Field number for the "max_deposit_period" field.</summary>
    public const int MaxDepositPeriodFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Duration maxDepositPeriod_;
    /// <summary>
    ///  Maximum period for Atom holders to deposit on a proposal. Initial value: 2
    ///  months.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Duration MaxDepositPeriod {
      get { return maxDepositPeriod_; }
      set {
        maxDepositPeriod_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DepositParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DepositParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!minDeposit_.Equals(other.minDeposit_)) return false;
      if (!object.Equals(MaxDepositPeriod, other.MaxDepositPeriod)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= minDeposit_.GetHashCode();
      if (maxDepositPeriod_ != null) hash ^= MaxDepositPeriod.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      minDeposit_.WriteTo(output, _repeated_minDeposit_codec);
      if (maxDepositPeriod_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MaxDepositPeriod);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      minDeposit_.WriteTo(ref output, _repeated_minDeposit_codec);
      if (maxDepositPeriod_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MaxDepositPeriod);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += minDeposit_.CalculateSize(_repeated_minDeposit_codec);
      if (maxDepositPeriod_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MaxDepositPeriod);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DepositParams other) {
      if (other == null) {
        return;
      }
      minDeposit_.Add(other.minDeposit_);
      if (other.maxDepositPeriod_ != null) {
        if (maxDepositPeriod_ == null) {
          MaxDepositPeriod = new global::Google.Protobuf.WellKnownTypes.Duration();
        }
        MaxDepositPeriod.MergeFrom(other.MaxDepositPeriod);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            minDeposit_.AddEntriesFrom(input, _repeated_minDeposit_codec);
            break;
          }
          case 18: {
            if (maxDepositPeriod_ == null) {
              MaxDepositPeriod = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(MaxDepositPeriod);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            minDeposit_.AddEntriesFrom(ref input, _repeated_minDeposit_codec);
            break;
          }
          case 18: {
            if (maxDepositPeriod_ == null) {
              MaxDepositPeriod = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(MaxDepositPeriod);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// VotingParams defines the params for voting on governance proposals.
  /// </summary>
  public sealed partial class VotingParams : pb::IMessage<VotingParams>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VotingParams> _parser = new pb::MessageParser<VotingParams>(() => new VotingParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VotingParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cosmos.Gov.V1.GovReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VotingParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VotingParams(VotingParams other) : this() {
      votingPeriod_ = other.votingPeriod_ != null ? other.votingPeriod_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VotingParams Clone() {
      return new VotingParams(this);
    }

    /// <summary>Field number for the "voting_period" field.</summary>
    public const int VotingPeriodFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Duration votingPeriod_;
    /// <summary>
    ///  Length of the voting period.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Duration VotingPeriod {
      get { return votingPeriod_; }
      set {
        votingPeriod_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VotingParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VotingParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(VotingPeriod, other.VotingPeriod)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (votingPeriod_ != null) hash ^= VotingPeriod.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (votingPeriod_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(VotingPeriod);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (votingPeriod_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(VotingPeriod);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (votingPeriod_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VotingPeriod);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VotingParams other) {
      if (other == null) {
        return;
      }
      if (other.votingPeriod_ != null) {
        if (votingPeriod_ == null) {
          VotingPeriod = new global::Google.Protobuf.WellKnownTypes.Duration();
        }
        VotingPeriod.MergeFrom(other.VotingPeriod);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (votingPeriod_ == null) {
              VotingPeriod = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(VotingPeriod);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (votingPeriod_ == null) {
              VotingPeriod = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(VotingPeriod);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// TallyParams defines the params for tallying votes on governance proposals.
  /// </summary>
  public sealed partial class TallyParams : pb::IMessage<TallyParams>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TallyParams> _parser = new pb::MessageParser<TallyParams>(() => new TallyParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TallyParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cosmos.Gov.V1.GovReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TallyParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TallyParams(TallyParams other) : this() {
      quorum_ = other.quorum_;
      threshold_ = other.threshold_;
      vetoThreshold_ = other.vetoThreshold_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TallyParams Clone() {
      return new TallyParams(this);
    }

    /// <summary>Field number for the "quorum" field.</summary>
    public const int QuorumFieldNumber = 1;
    private string quorum_ = "";
    /// <summary>
    ///  Minimum percentage of total stake needed to vote for a result to be
    ///  considered valid.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Quorum {
      get { return quorum_; }
      set {
        quorum_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "threshold" field.</summary>
    public const int ThresholdFieldNumber = 2;
    private string threshold_ = "";
    /// <summary>
    ///  Minimum proportion of Yes votes for proposal to pass. Default value: 0.5.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Threshold {
      get { return threshold_; }
      set {
        threshold_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "veto_threshold" field.</summary>
    public const int VetoThresholdFieldNumber = 3;
    private string vetoThreshold_ = "";
    /// <summary>
    ///  Minimum value of Veto votes to Total votes ratio for proposal to be
    ///  vetoed. Default value: 1/3.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VetoThreshold {
      get { return vetoThreshold_; }
      set {
        vetoThreshold_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TallyParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TallyParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Quorum != other.Quorum) return false;
      if (Threshold != other.Threshold) return false;
      if (VetoThreshold != other.VetoThreshold) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Quorum.Length != 0) hash ^= Quorum.GetHashCode();
      if (Threshold.Length != 0) hash ^= Threshold.GetHashCode();
      if (VetoThreshold.Length != 0) hash ^= VetoThreshold.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Quorum.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Quorum);
      }
      if (Threshold.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Threshold);
      }
      if (VetoThreshold.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(VetoThreshold);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Quorum.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Quorum);
      }
      if (Threshold.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Threshold);
      }
      if (VetoThreshold.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(VetoThreshold);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Quorum.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Quorum);
      }
      if (Threshold.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Threshold);
      }
      if (VetoThreshold.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VetoThreshold);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TallyParams other) {
      if (other == null) {
        return;
      }
      if (other.Quorum.Length != 0) {
        Quorum = other.Quorum;
      }
      if (other.Threshold.Length != 0) {
        Threshold = other.Threshold;
      }
      if (other.VetoThreshold.Length != 0) {
        VetoThreshold = other.VetoThreshold;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Quorum = input.ReadString();
            break;
          }
          case 18: {
            Threshold = input.ReadString();
            break;
          }
          case 26: {
            VetoThreshold = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Quorum = input.ReadString();
            break;
          }
          case 18: {
            Threshold = input.ReadString();
            break;
          }
          case 26: {
            VetoThreshold = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
