// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ibc/core/client/v1/tx.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ibc.Core.Client.V1 {

  /// <summary>Holder for reflection information generated from ibc/core/client/v1/tx.proto</summary>
  public static partial class TxReflection {

    #region Descriptor
    /// <summary>File descriptor for ibc/core/client/v1/tx.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TxReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtpYmMvY29yZS9jbGllbnQvdjEvdHgucHJvdG8SEmliYy5jb3JlLmNsaWVu",
            "dC52MRoUZ29nb3Byb3RvL2dvZ28ucHJvdG8aGWdvb2dsZS9wcm90b2J1Zi9h",
            "bnkucHJvdG8iuwEKD01zZ0NyZWF0ZUNsaWVudBJDCgxjbGllbnRfc3RhdGUY",
            "ASABKAsyFC5nb29nbGUucHJvdG9idWYuQW55Qhfy3h8TeWFtbDoiY2xpZW50",
            "X3N0YXRlIhJJCg9jb25zZW5zdXNfc3RhdGUYAiABKAsyFC5nb29nbGUucHJv",
            "dG9idWYuQW55Qhry3h8WeWFtbDoiY29uc2Vuc3VzX3N0YXRlIhIOCgZzaWdu",
            "ZXIYAyABKAk6COigHwCIoB8AIhkKF01zZ0NyZWF0ZUNsaWVudFJlc3BvbnNl",
            "InoKD01zZ1VwZGF0ZUNsaWVudBInCgljbGllbnRfaWQYASABKAlCFPLeHxB5",
            "YW1sOiJjbGllbnRfaWQiEiQKBmhlYWRlchgCIAEoCzIULmdvb2dsZS5wcm90",
            "b2J1Zi5BbnkSDgoGc2lnbmVyGAMgASgJOgjooB8AiKAfACIZChdNc2dVcGRh",
            "dGVDbGllbnRSZXNwb25zZSL1AgoQTXNnVXBncmFkZUNsaWVudBInCgljbGll",
            "bnRfaWQYASABKAlCFPLeHxB5YW1sOiJjbGllbnRfaWQiEkMKDGNsaWVudF9z",
            "dGF0ZRgCIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnlCF/LeHxN5YW1sOiJj",
            "bGllbnRfc3RhdGUiEkkKD2NvbnNlbnN1c19zdGF0ZRgDIAEoCzIULmdvb2ds",
            "ZS5wcm90b2J1Zi5BbnlCGvLeHxZ5YW1sOiJjb25zZW5zdXNfc3RhdGUiEj0K",
            "FHByb29mX3VwZ3JhZGVfY2xpZW50GAQgASgMQh/y3h8beWFtbDoicHJvb2Zf",
            "dXBncmFkZV9jbGllbnQiEk8KHXByb29mX3VwZ3JhZGVfY29uc2Vuc3VzX3N0",
            "YXRlGAUgASgMQijy3h8keWFtbDoicHJvb2ZfdXBncmFkZV9jb25zZW5zdXNf",
            "c3RhdGUiEg4KBnNpZ25lchgGIAEoCToI6KAfAIigHwAiGgoYTXNnVXBncmFk",
            "ZUNsaWVudFJlc3BvbnNlIoYBChVNc2dTdWJtaXRNaXNiZWhhdmlvdXISJwoJ",
            "Y2xpZW50X2lkGAEgASgJQhTy3h8QeWFtbDoiY2xpZW50X2lkIhIqCgxtaXNi",
            "ZWhhdmlvdXIYAiABKAsyFC5nb29nbGUucHJvdG9idWYuQW55Eg4KBnNpZ25l",
            "chgDIAEoCToI6KAfAIigHwAiHwodTXNnU3VibWl0TWlzYmVoYXZpb3VyUmVz",
            "cG9uc2UyogMKA01zZxJgCgxDcmVhdGVDbGllbnQSIy5pYmMuY29yZS5jbGll",
            "bnQudjEuTXNnQ3JlYXRlQ2xpZW50GisuaWJjLmNvcmUuY2xpZW50LnYxLk1z",
            "Z0NyZWF0ZUNsaWVudFJlc3BvbnNlEmAKDFVwZGF0ZUNsaWVudBIjLmliYy5j",
            "b3JlLmNsaWVudC52MS5Nc2dVcGRhdGVDbGllbnQaKy5pYmMuY29yZS5jbGll",
            "bnQudjEuTXNnVXBkYXRlQ2xpZW50UmVzcG9uc2USYwoNVXBncmFkZUNsaWVu",
            "dBIkLmliYy5jb3JlLmNsaWVudC52MS5Nc2dVcGdyYWRlQ2xpZW50GiwuaWJj",
            "LmNvcmUuY2xpZW50LnYxLk1zZ1VwZ3JhZGVDbGllbnRSZXNwb25zZRJyChJT",
            "dWJtaXRNaXNiZWhhdmlvdXISKS5pYmMuY29yZS5jbGllbnQudjEuTXNnU3Vi",
            "bWl0TWlzYmVoYXZpb3VyGjEuaWJjLmNvcmUuY2xpZW50LnYxLk1zZ1N1Ym1p",
            "dE1pc2JlaGF2aW91clJlc3BvbnNlQjpaOGdpdGh1Yi5jb20vY29zbW9zL2li",
            "Yy1nby92My9tb2R1bGVzL2NvcmUvMDItY2xpZW50L3R5cGVzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Gogoproto.GogoReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ibc.Core.Client.V1.MsgCreateClient), global::Ibc.Core.Client.V1.MsgCreateClient.Parser, new[]{ "ClientState", "ConsensusState", "Signer" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ibc.Core.Client.V1.MsgCreateClientResponse), global::Ibc.Core.Client.V1.MsgCreateClientResponse.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ibc.Core.Client.V1.MsgUpdateClient), global::Ibc.Core.Client.V1.MsgUpdateClient.Parser, new[]{ "ClientId", "Header", "Signer" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ibc.Core.Client.V1.MsgUpdateClientResponse), global::Ibc.Core.Client.V1.MsgUpdateClientResponse.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ibc.Core.Client.V1.MsgUpgradeClient), global::Ibc.Core.Client.V1.MsgUpgradeClient.Parser, new[]{ "ClientId", "ClientState", "ConsensusState", "ProofUpgradeClient", "ProofUpgradeConsensusState", "Signer" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ibc.Core.Client.V1.MsgUpgradeClientResponse), global::Ibc.Core.Client.V1.MsgUpgradeClientResponse.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ibc.Core.Client.V1.MsgSubmitMisbehaviour), global::Ibc.Core.Client.V1.MsgSubmitMisbehaviour.Parser, new[]{ "ClientId", "Misbehaviour", "Signer" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ibc.Core.Client.V1.MsgSubmitMisbehaviourResponse), global::Ibc.Core.Client.V1.MsgSubmitMisbehaviourResponse.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// MsgCreateClient defines a message to create an IBC client
  /// </summary>
  public sealed partial class MsgCreateClient : pb::IMessage<MsgCreateClient>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgCreateClient> _parser = new pb::MessageParser<MsgCreateClient>(() => new MsgCreateClient());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgCreateClient> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ibc.Core.Client.V1.TxReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgCreateClient() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgCreateClient(MsgCreateClient other) : this() {
      clientState_ = other.clientState_ != null ? other.clientState_.Clone() : null;
      consensusState_ = other.consensusState_ != null ? other.consensusState_.Clone() : null;
      signer_ = other.signer_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgCreateClient Clone() {
      return new MsgCreateClient(this);
    }

    /// <summary>Field number for the "client_state" field.</summary>
    public const int ClientStateFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Any clientState_;
    /// <summary>
    /// light client state
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any ClientState {
      get { return clientState_; }
      set {
        clientState_ = value;
      }
    }

    /// <summary>Field number for the "consensus_state" field.</summary>
    public const int ConsensusStateFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any consensusState_;
    /// <summary>
    /// consensus state associated with the client that corresponds to a given
    /// height.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any ConsensusState {
      get { return consensusState_; }
      set {
        consensusState_ = value;
      }
    }

    /// <summary>Field number for the "signer" field.</summary>
    public const int SignerFieldNumber = 3;
    private string signer_ = "";
    /// <summary>
    /// signer address
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Signer {
      get { return signer_; }
      set {
        signer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgCreateClient);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgCreateClient other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ClientState, other.ClientState)) return false;
      if (!object.Equals(ConsensusState, other.ConsensusState)) return false;
      if (Signer != other.Signer) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (clientState_ != null) hash ^= ClientState.GetHashCode();
      if (consensusState_ != null) hash ^= ConsensusState.GetHashCode();
      if (Signer.Length != 0) hash ^= Signer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (clientState_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ClientState);
      }
      if (consensusState_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ConsensusState);
      }
      if (Signer.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Signer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (clientState_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ClientState);
      }
      if (consensusState_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ConsensusState);
      }
      if (Signer.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Signer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (clientState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClientState);
      }
      if (consensusState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ConsensusState);
      }
      if (Signer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Signer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgCreateClient other) {
      if (other == null) {
        return;
      }
      if (other.clientState_ != null) {
        if (clientState_ == null) {
          ClientState = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        ClientState.MergeFrom(other.ClientState);
      }
      if (other.consensusState_ != null) {
        if (consensusState_ == null) {
          ConsensusState = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        ConsensusState.MergeFrom(other.ConsensusState);
      }
      if (other.Signer.Length != 0) {
        Signer = other.Signer;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (clientState_ == null) {
              ClientState = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ClientState);
            break;
          }
          case 18: {
            if (consensusState_ == null) {
              ConsensusState = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ConsensusState);
            break;
          }
          case 26: {
            Signer = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (clientState_ == null) {
              ClientState = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ClientState);
            break;
          }
          case 18: {
            if (consensusState_ == null) {
              ConsensusState = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ConsensusState);
            break;
          }
          case 26: {
            Signer = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// MsgCreateClientResponse defines the Msg/CreateClient response type.
  /// </summary>
  public sealed partial class MsgCreateClientResponse : pb::IMessage<MsgCreateClientResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgCreateClientResponse> _parser = new pb::MessageParser<MsgCreateClientResponse>(() => new MsgCreateClientResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgCreateClientResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ibc.Core.Client.V1.TxReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgCreateClientResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgCreateClientResponse(MsgCreateClientResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgCreateClientResponse Clone() {
      return new MsgCreateClientResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgCreateClientResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgCreateClientResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgCreateClientResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  /// MsgUpdateClient defines an sdk.Msg to update a IBC client state using
  /// the given header.
  /// </summary>
  public sealed partial class MsgUpdateClient : pb::IMessage<MsgUpdateClient>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgUpdateClient> _parser = new pb::MessageParser<MsgUpdateClient>(() => new MsgUpdateClient());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgUpdateClient> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ibc.Core.Client.V1.TxReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgUpdateClient() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgUpdateClient(MsgUpdateClient other) : this() {
      clientId_ = other.clientId_;
      header_ = other.header_ != null ? other.header_.Clone() : null;
      signer_ = other.signer_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgUpdateClient Clone() {
      return new MsgUpdateClient(this);
    }

    /// <summary>Field number for the "client_id" field.</summary>
    public const int ClientIdFieldNumber = 1;
    private string clientId_ = "";
    /// <summary>
    /// client unique identifier
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientId {
      get { return clientId_; }
      set {
        clientId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any header_;
    /// <summary>
    /// header to update the light client
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "signer" field.</summary>
    public const int SignerFieldNumber = 3;
    private string signer_ = "";
    /// <summary>
    /// signer address
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Signer {
      get { return signer_; }
      set {
        signer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgUpdateClient);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgUpdateClient other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientId != other.ClientId) return false;
      if (!object.Equals(Header, other.Header)) return false;
      if (Signer != other.Signer) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientId.Length != 0) hash ^= ClientId.GetHashCode();
      if (header_ != null) hash ^= Header.GetHashCode();
      if (Signer.Length != 0) hash ^= Signer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientId);
      }
      if (header_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Header);
      }
      if (Signer.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Signer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientId);
      }
      if (header_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Header);
      }
      if (Signer.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Signer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientId);
      }
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (Signer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Signer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgUpdateClient other) {
      if (other == null) {
        return;
      }
      if (other.ClientId.Length != 0) {
        ClientId = other.ClientId;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.Signer.Length != 0) {
        Signer = other.Signer;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientId = input.ReadString();
            break;
          }
          case 18: {
            if (header_ == null) {
              Header = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Header);
            break;
          }
          case 26: {
            Signer = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ClientId = input.ReadString();
            break;
          }
          case 18: {
            if (header_ == null) {
              Header = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Header);
            break;
          }
          case 26: {
            Signer = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// MsgUpdateClientResponse defines the Msg/UpdateClient response type.
  /// </summary>
  public sealed partial class MsgUpdateClientResponse : pb::IMessage<MsgUpdateClientResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgUpdateClientResponse> _parser = new pb::MessageParser<MsgUpdateClientResponse>(() => new MsgUpdateClientResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgUpdateClientResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ibc.Core.Client.V1.TxReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgUpdateClientResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgUpdateClientResponse(MsgUpdateClientResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgUpdateClientResponse Clone() {
      return new MsgUpdateClientResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgUpdateClientResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgUpdateClientResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgUpdateClientResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  /// MsgUpgradeClient defines an sdk.Msg to upgrade an IBC client to a new client
  /// state
  /// </summary>
  public sealed partial class MsgUpgradeClient : pb::IMessage<MsgUpgradeClient>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgUpgradeClient> _parser = new pb::MessageParser<MsgUpgradeClient>(() => new MsgUpgradeClient());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgUpgradeClient> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ibc.Core.Client.V1.TxReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgUpgradeClient() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgUpgradeClient(MsgUpgradeClient other) : this() {
      clientId_ = other.clientId_;
      clientState_ = other.clientState_ != null ? other.clientState_.Clone() : null;
      consensusState_ = other.consensusState_ != null ? other.consensusState_.Clone() : null;
      proofUpgradeClient_ = other.proofUpgradeClient_;
      proofUpgradeConsensusState_ = other.proofUpgradeConsensusState_;
      signer_ = other.signer_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgUpgradeClient Clone() {
      return new MsgUpgradeClient(this);
    }

    /// <summary>Field number for the "client_id" field.</summary>
    public const int ClientIdFieldNumber = 1;
    private string clientId_ = "";
    /// <summary>
    /// client unique identifier
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientId {
      get { return clientId_; }
      set {
        clientId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "client_state" field.</summary>
    public const int ClientStateFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any clientState_;
    /// <summary>
    /// upgraded client state
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any ClientState {
      get { return clientState_; }
      set {
        clientState_ = value;
      }
    }

    /// <summary>Field number for the "consensus_state" field.</summary>
    public const int ConsensusStateFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Any consensusState_;
    /// <summary>
    /// upgraded consensus state, only contains enough information to serve as a
    /// basis of trust in update logic
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any ConsensusState {
      get { return consensusState_; }
      set {
        consensusState_ = value;
      }
    }

    /// <summary>Field number for the "proof_upgrade_client" field.</summary>
    public const int ProofUpgradeClientFieldNumber = 4;
    private pb::ByteString proofUpgradeClient_ = pb::ByteString.Empty;
    /// <summary>
    /// proof that old chain committed to new client
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ProofUpgradeClient {
      get { return proofUpgradeClient_; }
      set {
        proofUpgradeClient_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "proof_upgrade_consensus_state" field.</summary>
    public const int ProofUpgradeConsensusStateFieldNumber = 5;
    private pb::ByteString proofUpgradeConsensusState_ = pb::ByteString.Empty;
    /// <summary>
    /// proof that old chain committed to new consensus state
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ProofUpgradeConsensusState {
      get { return proofUpgradeConsensusState_; }
      set {
        proofUpgradeConsensusState_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "signer" field.</summary>
    public const int SignerFieldNumber = 6;
    private string signer_ = "";
    /// <summary>
    /// signer address
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Signer {
      get { return signer_; }
      set {
        signer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgUpgradeClient);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgUpgradeClient other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientId != other.ClientId) return false;
      if (!object.Equals(ClientState, other.ClientState)) return false;
      if (!object.Equals(ConsensusState, other.ConsensusState)) return false;
      if (ProofUpgradeClient != other.ProofUpgradeClient) return false;
      if (ProofUpgradeConsensusState != other.ProofUpgradeConsensusState) return false;
      if (Signer != other.Signer) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientId.Length != 0) hash ^= ClientId.GetHashCode();
      if (clientState_ != null) hash ^= ClientState.GetHashCode();
      if (consensusState_ != null) hash ^= ConsensusState.GetHashCode();
      if (ProofUpgradeClient.Length != 0) hash ^= ProofUpgradeClient.GetHashCode();
      if (ProofUpgradeConsensusState.Length != 0) hash ^= ProofUpgradeConsensusState.GetHashCode();
      if (Signer.Length != 0) hash ^= Signer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientId);
      }
      if (clientState_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ClientState);
      }
      if (consensusState_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ConsensusState);
      }
      if (ProofUpgradeClient.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(ProofUpgradeClient);
      }
      if (ProofUpgradeConsensusState.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(ProofUpgradeConsensusState);
      }
      if (Signer.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Signer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientId);
      }
      if (clientState_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ClientState);
      }
      if (consensusState_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ConsensusState);
      }
      if (ProofUpgradeClient.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(ProofUpgradeClient);
      }
      if (ProofUpgradeConsensusState.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(ProofUpgradeConsensusState);
      }
      if (Signer.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Signer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientId);
      }
      if (clientState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClientState);
      }
      if (consensusState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ConsensusState);
      }
      if (ProofUpgradeClient.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ProofUpgradeClient);
      }
      if (ProofUpgradeConsensusState.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ProofUpgradeConsensusState);
      }
      if (Signer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Signer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgUpgradeClient other) {
      if (other == null) {
        return;
      }
      if (other.ClientId.Length != 0) {
        ClientId = other.ClientId;
      }
      if (other.clientState_ != null) {
        if (clientState_ == null) {
          ClientState = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        ClientState.MergeFrom(other.ClientState);
      }
      if (other.consensusState_ != null) {
        if (consensusState_ == null) {
          ConsensusState = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        ConsensusState.MergeFrom(other.ConsensusState);
      }
      if (other.ProofUpgradeClient.Length != 0) {
        ProofUpgradeClient = other.ProofUpgradeClient;
      }
      if (other.ProofUpgradeConsensusState.Length != 0) {
        ProofUpgradeConsensusState = other.ProofUpgradeConsensusState;
      }
      if (other.Signer.Length != 0) {
        Signer = other.Signer;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientId = input.ReadString();
            break;
          }
          case 18: {
            if (clientState_ == null) {
              ClientState = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ClientState);
            break;
          }
          case 26: {
            if (consensusState_ == null) {
              ConsensusState = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ConsensusState);
            break;
          }
          case 34: {
            ProofUpgradeClient = input.ReadBytes();
            break;
          }
          case 42: {
            ProofUpgradeConsensusState = input.ReadBytes();
            break;
          }
          case 50: {
            Signer = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ClientId = input.ReadString();
            break;
          }
          case 18: {
            if (clientState_ == null) {
              ClientState = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ClientState);
            break;
          }
          case 26: {
            if (consensusState_ == null) {
              ConsensusState = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ConsensusState);
            break;
          }
          case 34: {
            ProofUpgradeClient = input.ReadBytes();
            break;
          }
          case 42: {
            ProofUpgradeConsensusState = input.ReadBytes();
            break;
          }
          case 50: {
            Signer = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// MsgUpgradeClientResponse defines the Msg/UpgradeClient response type.
  /// </summary>
  public sealed partial class MsgUpgradeClientResponse : pb::IMessage<MsgUpgradeClientResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgUpgradeClientResponse> _parser = new pb::MessageParser<MsgUpgradeClientResponse>(() => new MsgUpgradeClientResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgUpgradeClientResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ibc.Core.Client.V1.TxReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgUpgradeClientResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgUpgradeClientResponse(MsgUpgradeClientResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgUpgradeClientResponse Clone() {
      return new MsgUpgradeClientResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgUpgradeClientResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgUpgradeClientResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgUpgradeClientResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  /// MsgSubmitMisbehaviour defines an sdk.Msg type that submits Evidence for
  /// light client misbehaviour.
  /// </summary>
  public sealed partial class MsgSubmitMisbehaviour : pb::IMessage<MsgSubmitMisbehaviour>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgSubmitMisbehaviour> _parser = new pb::MessageParser<MsgSubmitMisbehaviour>(() => new MsgSubmitMisbehaviour());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgSubmitMisbehaviour> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ibc.Core.Client.V1.TxReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgSubmitMisbehaviour() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgSubmitMisbehaviour(MsgSubmitMisbehaviour other) : this() {
      clientId_ = other.clientId_;
      misbehaviour_ = other.misbehaviour_ != null ? other.misbehaviour_.Clone() : null;
      signer_ = other.signer_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgSubmitMisbehaviour Clone() {
      return new MsgSubmitMisbehaviour(this);
    }

    /// <summary>Field number for the "client_id" field.</summary>
    public const int ClientIdFieldNumber = 1;
    private string clientId_ = "";
    /// <summary>
    /// client unique identifier
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientId {
      get { return clientId_; }
      set {
        clientId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "misbehaviour" field.</summary>
    public const int MisbehaviourFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any misbehaviour_;
    /// <summary>
    /// misbehaviour used for freezing the light client
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Misbehaviour {
      get { return misbehaviour_; }
      set {
        misbehaviour_ = value;
      }
    }

    /// <summary>Field number for the "signer" field.</summary>
    public const int SignerFieldNumber = 3;
    private string signer_ = "";
    /// <summary>
    /// signer address
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Signer {
      get { return signer_; }
      set {
        signer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgSubmitMisbehaviour);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgSubmitMisbehaviour other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientId != other.ClientId) return false;
      if (!object.Equals(Misbehaviour, other.Misbehaviour)) return false;
      if (Signer != other.Signer) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientId.Length != 0) hash ^= ClientId.GetHashCode();
      if (misbehaviour_ != null) hash ^= Misbehaviour.GetHashCode();
      if (Signer.Length != 0) hash ^= Signer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientId);
      }
      if (misbehaviour_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Misbehaviour);
      }
      if (Signer.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Signer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientId);
      }
      if (misbehaviour_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Misbehaviour);
      }
      if (Signer.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Signer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientId);
      }
      if (misbehaviour_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Misbehaviour);
      }
      if (Signer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Signer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgSubmitMisbehaviour other) {
      if (other == null) {
        return;
      }
      if (other.ClientId.Length != 0) {
        ClientId = other.ClientId;
      }
      if (other.misbehaviour_ != null) {
        if (misbehaviour_ == null) {
          Misbehaviour = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Misbehaviour.MergeFrom(other.Misbehaviour);
      }
      if (other.Signer.Length != 0) {
        Signer = other.Signer;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientId = input.ReadString();
            break;
          }
          case 18: {
            if (misbehaviour_ == null) {
              Misbehaviour = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Misbehaviour);
            break;
          }
          case 26: {
            Signer = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ClientId = input.ReadString();
            break;
          }
          case 18: {
            if (misbehaviour_ == null) {
              Misbehaviour = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Misbehaviour);
            break;
          }
          case 26: {
            Signer = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// MsgSubmitMisbehaviourResponse defines the Msg/SubmitMisbehaviour response
  /// type.
  /// </summary>
  public sealed partial class MsgSubmitMisbehaviourResponse : pb::IMessage<MsgSubmitMisbehaviourResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgSubmitMisbehaviourResponse> _parser = new pb::MessageParser<MsgSubmitMisbehaviourResponse>(() => new MsgSubmitMisbehaviourResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgSubmitMisbehaviourResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ibc.Core.Client.V1.TxReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgSubmitMisbehaviourResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgSubmitMisbehaviourResponse(MsgSubmitMisbehaviourResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgSubmitMisbehaviourResponse Clone() {
      return new MsgSubmitMisbehaviourResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgSubmitMisbehaviourResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgSubmitMisbehaviourResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgSubmitMisbehaviourResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
