// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ibc/applications/transfer/v1/tx.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ibc.Applications.Transfer.V1 {

  /// <summary>Holder for reflection information generated from ibc/applications/transfer/v1/tx.proto</summary>
  public static partial class TxReflection {

    #region Descriptor
    /// <summary>File descriptor for ibc/applications/transfer/v1/tx.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TxReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVpYmMvYXBwbGljYXRpb25zL3RyYW5zZmVyL3YxL3R4LnByb3RvEhxpYmMu",
            "YXBwbGljYXRpb25zLnRyYW5zZmVyLnYxGhRnb2dvcHJvdG8vZ29nby5wcm90",
            "bxoeY29zbW9zL2Jhc2UvdjFiZXRhMS9jb2luLnByb3RvGh9pYmMvY29yZS9j",
            "bGllbnQvdjEvY2xpZW50LnByb3RvItUCCgtNc2dUcmFuc2ZlchIrCgtzb3Vy",
            "Y2VfcG9ydBgBIAEoCUIW8t4fEnlhbWw6InNvdXJjZV9wb3J0IhIxCg5zb3Vy",
            "Y2VfY2hhbm5lbBgCIAEoCUIZ8t4fFXlhbWw6InNvdXJjZV9jaGFubmVsIhIu",
            "CgV0b2tlbhgDIAEoCzIZLmNvc21vcy5iYXNlLnYxYmV0YTEuQ29pbkIEyN4f",
            "ABIOCgZzZW5kZXIYBCABKAkSEAoIcmVjZWl2ZXIYBSABKAkSUQoOdGltZW91",
            "dF9oZWlnaHQYBiABKAsyGi5pYmMuY29yZS5jbGllbnQudjEuSGVpZ2h0Qh3y",
            "3h8VeWFtbDoidGltZW91dF9oZWlnaHQiyN4fABI3ChF0aW1lb3V0X3RpbWVz",
            "dGFtcBgHIAEoBEIc8t4fGHlhbWw6InRpbWVvdXRfdGltZXN0YW1wIjoI6KAf",
            "AIigHwAiFQoTTXNnVHJhbnNmZXJSZXNwb25zZTJvCgNNc2cSaAoIVHJhbnNm",
            "ZXISKS5pYmMuYXBwbGljYXRpb25zLnRyYW5zZmVyLnYxLk1zZ1RyYW5zZmVy",
            "GjEuaWJjLmFwcGxpY2F0aW9ucy50cmFuc2Zlci52MS5Nc2dUcmFuc2ZlclJl",
            "c3BvbnNlQjlaN2dpdGh1Yi5jb20vY29zbW9zL2liYy1nby92My9tb2R1bGVz",
            "L2FwcHMvdHJhbnNmZXIvdHlwZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Gogoproto.GogoReflection.Descriptor, global::Cosmos.Base.V1Beta1.CoinReflection.Descriptor, global::Ibc.Core.Client.V1.ClientReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ibc.Applications.Transfer.V1.MsgTransfer), global::Ibc.Applications.Transfer.V1.MsgTransfer.Parser, new[]{ "SourcePort", "SourceChannel", "Token", "Sender", "Receiver", "TimeoutHeight", "TimeoutTimestamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ibc.Applications.Transfer.V1.MsgTransferResponse), global::Ibc.Applications.Transfer.V1.MsgTransferResponse.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// MsgTransfer defines a msg to transfer fungible tokens (i.e Coins) between
  /// ICS20 enabled chains. See ICS Spec here:
  /// https://github.com/cosmos/ibc/tree/master/spec/app/ics-020-fungible-token-transfer#data-structures
  /// </summary>
  public sealed partial class MsgTransfer : pb::IMessage<MsgTransfer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgTransfer> _parser = new pb::MessageParser<MsgTransfer>(() => new MsgTransfer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgTransfer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ibc.Applications.Transfer.V1.TxReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgTransfer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgTransfer(MsgTransfer other) : this() {
      sourcePort_ = other.sourcePort_;
      sourceChannel_ = other.sourceChannel_;
      token_ = other.token_ != null ? other.token_.Clone() : null;
      sender_ = other.sender_;
      receiver_ = other.receiver_;
      timeoutHeight_ = other.timeoutHeight_ != null ? other.timeoutHeight_.Clone() : null;
      timeoutTimestamp_ = other.timeoutTimestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgTransfer Clone() {
      return new MsgTransfer(this);
    }

    /// <summary>Field number for the "source_port" field.</summary>
    public const int SourcePortFieldNumber = 1;
    private string sourcePort_ = "";
    /// <summary>
    /// the port on which the packet will be sent
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SourcePort {
      get { return sourcePort_; }
      set {
        sourcePort_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "source_channel" field.</summary>
    public const int SourceChannelFieldNumber = 2;
    private string sourceChannel_ = "";
    /// <summary>
    /// the channel by which the packet will be sent
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SourceChannel {
      get { return sourceChannel_; }
      set {
        sourceChannel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 3;
    private global::Cosmos.Base.V1Beta1.Coin token_;
    /// <summary>
    /// the tokens to be transferred
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cosmos.Base.V1Beta1.Coin Token {
      get { return token_; }
      set {
        token_ = value;
      }
    }

    /// <summary>Field number for the "sender" field.</summary>
    public const int SenderFieldNumber = 4;
    private string sender_ = "";
    /// <summary>
    /// the sender address
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Sender {
      get { return sender_; }
      set {
        sender_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "receiver" field.</summary>
    public const int ReceiverFieldNumber = 5;
    private string receiver_ = "";
    /// <summary>
    /// the recipient address on the destination chain
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Receiver {
      get { return receiver_; }
      set {
        receiver_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timeout_height" field.</summary>
    public const int TimeoutHeightFieldNumber = 6;
    private global::Ibc.Core.Client.V1.Height timeoutHeight_;
    /// <summary>
    /// Timeout height relative to the current block height.
    /// The timeout is disabled when set to 0.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ibc.Core.Client.V1.Height TimeoutHeight {
      get { return timeoutHeight_; }
      set {
        timeoutHeight_ = value;
      }
    }

    /// <summary>Field number for the "timeout_timestamp" field.</summary>
    public const int TimeoutTimestampFieldNumber = 7;
    private ulong timeoutTimestamp_;
    /// <summary>
    /// Timeout timestamp in absolute nanoseconds since unix epoch.
    /// The timeout is disabled when set to 0.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TimeoutTimestamp {
      get { return timeoutTimestamp_; }
      set {
        timeoutTimestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgTransfer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgTransfer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SourcePort != other.SourcePort) return false;
      if (SourceChannel != other.SourceChannel) return false;
      if (!object.Equals(Token, other.Token)) return false;
      if (Sender != other.Sender) return false;
      if (Receiver != other.Receiver) return false;
      if (!object.Equals(TimeoutHeight, other.TimeoutHeight)) return false;
      if (TimeoutTimestamp != other.TimeoutTimestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SourcePort.Length != 0) hash ^= SourcePort.GetHashCode();
      if (SourceChannel.Length != 0) hash ^= SourceChannel.GetHashCode();
      if (token_ != null) hash ^= Token.GetHashCode();
      if (Sender.Length != 0) hash ^= Sender.GetHashCode();
      if (Receiver.Length != 0) hash ^= Receiver.GetHashCode();
      if (timeoutHeight_ != null) hash ^= TimeoutHeight.GetHashCode();
      if (TimeoutTimestamp != 0UL) hash ^= TimeoutTimestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SourcePort.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SourcePort);
      }
      if (SourceChannel.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SourceChannel);
      }
      if (token_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Token);
      }
      if (Sender.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Sender);
      }
      if (Receiver.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Receiver);
      }
      if (timeoutHeight_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(TimeoutHeight);
      }
      if (TimeoutTimestamp != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(TimeoutTimestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SourcePort.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SourcePort);
      }
      if (SourceChannel.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SourceChannel);
      }
      if (token_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Token);
      }
      if (Sender.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Sender);
      }
      if (Receiver.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Receiver);
      }
      if (timeoutHeight_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(TimeoutHeight);
      }
      if (TimeoutTimestamp != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(TimeoutTimestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SourcePort.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SourcePort);
      }
      if (SourceChannel.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SourceChannel);
      }
      if (token_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Token);
      }
      if (Sender.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sender);
      }
      if (Receiver.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Receiver);
      }
      if (timeoutHeight_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeoutHeight);
      }
      if (TimeoutTimestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimeoutTimestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgTransfer other) {
      if (other == null) {
        return;
      }
      if (other.SourcePort.Length != 0) {
        SourcePort = other.SourcePort;
      }
      if (other.SourceChannel.Length != 0) {
        SourceChannel = other.SourceChannel;
      }
      if (other.token_ != null) {
        if (token_ == null) {
          Token = new global::Cosmos.Base.V1Beta1.Coin();
        }
        Token.MergeFrom(other.Token);
      }
      if (other.Sender.Length != 0) {
        Sender = other.Sender;
      }
      if (other.Receiver.Length != 0) {
        Receiver = other.Receiver;
      }
      if (other.timeoutHeight_ != null) {
        if (timeoutHeight_ == null) {
          TimeoutHeight = new global::Ibc.Core.Client.V1.Height();
        }
        TimeoutHeight.MergeFrom(other.TimeoutHeight);
      }
      if (other.TimeoutTimestamp != 0UL) {
        TimeoutTimestamp = other.TimeoutTimestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SourcePort = input.ReadString();
            break;
          }
          case 18: {
            SourceChannel = input.ReadString();
            break;
          }
          case 26: {
            if (token_ == null) {
              Token = new global::Cosmos.Base.V1Beta1.Coin();
            }
            input.ReadMessage(Token);
            break;
          }
          case 34: {
            Sender = input.ReadString();
            break;
          }
          case 42: {
            Receiver = input.ReadString();
            break;
          }
          case 50: {
            if (timeoutHeight_ == null) {
              TimeoutHeight = new global::Ibc.Core.Client.V1.Height();
            }
            input.ReadMessage(TimeoutHeight);
            break;
          }
          case 56: {
            TimeoutTimestamp = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SourcePort = input.ReadString();
            break;
          }
          case 18: {
            SourceChannel = input.ReadString();
            break;
          }
          case 26: {
            if (token_ == null) {
              Token = new global::Cosmos.Base.V1Beta1.Coin();
            }
            input.ReadMessage(Token);
            break;
          }
          case 34: {
            Sender = input.ReadString();
            break;
          }
          case 42: {
            Receiver = input.ReadString();
            break;
          }
          case 50: {
            if (timeoutHeight_ == null) {
              TimeoutHeight = new global::Ibc.Core.Client.V1.Height();
            }
            input.ReadMessage(TimeoutHeight);
            break;
          }
          case 56: {
            TimeoutTimestamp = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// MsgTransferResponse defines the Msg/Transfer response type.
  /// </summary>
  public sealed partial class MsgTransferResponse : pb::IMessage<MsgTransferResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgTransferResponse> _parser = new pb::MessageParser<MsgTransferResponse>(() => new MsgTransferResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgTransferResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ibc.Applications.Transfer.V1.TxReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgTransferResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgTransferResponse(MsgTransferResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgTransferResponse Clone() {
      return new MsgTransferResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgTransferResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgTransferResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgTransferResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
